"""first migration

Revision ID: 9e5ea5f19bb6
Revises: 
Create Date: 2022-05-10 17:06:24.963492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e5ea5f19bb6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('image', sa.String(length=250), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('watering', sa.String(length=250), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('place', sa.String(length=250), nullable=False),
    sa.Column('substrate_addition', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ph_value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(length=250), nullable=False),
    sa.Column('status', sa.String(length=250), nullable=False),
    sa.Column('watering_date', sa.DateTime(), nullable=True),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pot')
    op.drop_table('user')
    op.drop_table('plant')
    # ### end Alembic commands ###
